sudo: false

language: scala

scala:
  - 2.10.5
  - 2.11.6

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script: "sbt -sbt-version 0.13.7 clean coverage test"

after_success: "sbt -sbt-version 0.13.7 coveralls"

