sudo: false

language: scala

scala:
  - 2.10.5
  - 2.11.6

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script:
  - sbt ++2.10.5 test
  - sbt clean coverage test

after_success: "sbt coveralls"

